services:

  app:
    image: l4rm4nd/vouchervault:1.28.x
    container_name: vouchervault-dev
    restart: unless-stopped
    entrypoint: python3
    command: manage.py runserver 0.0.0.0:8000
    environment:
      - DOMAIN=192.168.86.47
      - SECURE_COOKIES=False
      - EXPIRY_THRESHOLD_DAYS=90
      - TZ=Europe/Dublin
      - SESSION_EXPIRE_AT_BROWSER_CLOSE=False
      - PYTHONDONTWRITEBYTECODE=1
      - DEBUG=True
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./volume-data/database:/opt/app/database
      - ./myapp:/opt/app/myapp
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: vouchervault-dev-redis
    restart: unless-stopped
    expose:
      - 6379
