# Generated by Django 5.2.15 on 2026-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_add_currency_to_item_and_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='balance_checker',
            field=models.CharField(choices=[('none', 'None (manual tracking)'), ('lidl_ie', 'Lidl Ireland'), ('dunnes_ie', 'Dunnes Stores Ireland'), ('supervalu_ie', 'SuperValu Ireland'), ('tesco_ie', 'Tesco Ireland')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='live_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
